[package]
name = "dmal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-xid = "0.2.2"
unic-emoji-char = "0.9.0"

[dev-dependencies]
expect-test = "1.2.2"
